
version: "3"

services:

  postgres:
    image: postgres:11.1-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    
  web:
    build: .
    tty: true
    command:  [ "./bin/wait-for-postgres.sh", "debug", "python3", "manage.py", "runserver", "0.0.0.0:8000" ]
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    user: "${UID}:${GID}"
