# Generated by Django 2.1.3 on 2018-11-27 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('namedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.NamedModel')),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Organization')),
            ],
            bases=('core.namedmodel',),
        ),
        migrations.CreateModel(
            name='TaskCategoryModel',
            fields=[
                ('namedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.NamedModel')),
            ],
            bases=('core.namedmodel',),
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('namedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.NamedModel')),
                ('category', models.ManyToManyField(to='project.TaskCategoryModel')),
            ],
            bases=('core.namedmodel',),
        ),
        migrations.AddField(
            model_name='contribution',
            name='task',
            field=models.ForeignKey(help_text='What should be done.', on_delete=django.db.models.deletion.PROTECT, to='project.TaskModel'),
        ),
    ]
