# Generated by Django 2.1.3 on 2018-11-27 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.CharField(blank=True, max_length=500, null=True)),
                ('full', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('namedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.NamedModel')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Organization')),
                ('perfectionnement', models.ManyToManyField(to='core.Formation')),
                ('scholarite', models.ManyToManyField(to='core.Scholarite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.User')),
            ],
            bases=('core.namedmodel',),
        ),
    ]
