# Generated by Django 2.1.3 on 2018-12-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titre du CV')),
                ('description', models.TextField(verbose_name='Description du CV')),
                ('prenom_consultant', models.CharField(max_length=50, verbose_name='Prénom du consultant')),
                ('nom_consultant', models.CharField(max_length=50, verbose_name='Nom du consultant')),
                ('titre_consultant', models.CharField(max_length=50, verbose_name='Titre du consultant')),
                ('date_de_naissance', models.DateField(verbose_name='Date de naissance')),
                ('courriel', models.EmailField(max_length=254, verbose_name='Courriel')),
                ('bureau', models.CharField(choices=[('M', 'Montréal'), ('Q', 'Québec')], default='M', max_length=2, verbose_name='Bureau')),
            ],
        ),
    ]
