# Generated by Django 2.1.3 on 2018-11-27 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person')),
                ('adresses', models.ManyToManyField(to='core.Address')),
                ('contributions', models.ManyToManyField(blank=True, to='core.Contribution')),
                ('interets', models.ManyToManyField(blank=True, to='core.Interest')),
                ('jobs', models.ManyToManyField(blank=True, to='core.Job')),
                ('qualities', models.ManyToManyField(blank=True, to='core.Quality')),
                ('skills', models.ManyToManyField(blank=True, to='core.Skill')),
            ],
            bases=('core.person',),
        ),
    ]
